# Generated by Django 6.0.2 on 2026-02-04 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='total',
            field=models.FloatField(default=0.0),
        ),
    ]
