# Generated by Django 6.0.2 on 2026-02-05 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_bill_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='product',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='billitem',
            name='price',
        ),
        migrations.RemoveField(
            model_name='billitem',
            name='quantity',
        ),
    ]
