# Generated by Django 6.0.2 on 2026-02-05 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_bill_product_remove_bill_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='total_price',
            field=models.FloatField(default=0.0),
        ),
    ]
