# Generated by Django 6.0.2 on 2026-02-05 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_bill_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='billitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
