# Generated by Django 6.0.2 on 2026-02-05 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_billitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='billitem',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
