# Generated by Django 6.0.2 on 2026-02-06 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_billitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='gst',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bill',
            name='tax',
            field=models.FloatField(default=0),
        ),
    ]
