# Generated by Django 6.0.2 on 2026-02-09 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_bill_gst_bill_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='item_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
