# Generated by Django 6.0.2 on 2026-02-09 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_bill_item_name_bill_phone_bill_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='bill_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
