# Generated by Django 6.0.2 on 2026-02-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_bill_bill_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_rate', models.FloatField(default=0.0)),
                ('gst_rate', models.FloatField(default=0.0)),
            ],
        ),
    ]
